<a href="https://colab.research.google.com/github/amamra-abdenour/Deep_Learning_Python/blob/master/DeepLearning_9.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
import numpy as np

samples = {'The cat ate my hat','The dog ate my homework'}
token_index = {}
print(type(token_index))
for sample in samples:
  for word in sample.split():
    if word not in token_index:
      token_index[word] = len(token_index) 
print(token_index)
max_length = 10
results = np.zeros(shape = (len(samples), max_length, max(token_index.values()) + 1))
for i, sample in enumerate(samples):
  for j, word in list(enumerate(sample.split()))[:max_length]:
    print(list(enumerate(sample.split())))
    index = token_index.get(word)
    results[i, j, index] = 1.



print(results)


<class 'dict'>
{'The': 0, 'dog': 1, 'ate': 2, 'my': 3, 'homework': 4, 'cat': 5, 'hat': 6}
[(0, 'The'), (1, 'dog'), (2, 'ate'), (3, 'my'), (4, 'homework')]
[(0, 'The'), (1, 'dog'), (2, 'ate'), (3, 'my'), (4, 'homework')]
[(0, 'The'), (1, 'dog'), (2, 'ate'), (3, 'my'), (4, 'homework')]
[(0, 'The'), (1, 'dog'), (2, 'ate'), (3, 'my'), (4, 'homework')]
[(0, 'The'), (1, 'dog'), (2, 'ate'), (3, 'my'), (4, 'homework')]
[(0, 'The'), (1, 'cat'), (2, 'ate'), (3, 'my'), (4, 'hat')]
[(0, 'The'), (1, 'cat'), (2, 'ate'), (3, 'my'), (4, 'hat')]
[(0, 'The'), (1, 'cat'), (2, 'ate'), (3, 'my'), (4, 'hat')]
[(0, 'The'), (1, 'cat'), (2, 'ate'), (3, 'my'), (4, 'hat')]
[(0, 'The'), (1, 'cat'), (2, 'ate'), (3, 'my'), (4, 'hat')]
[[[1. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[1. 0. 0. 0. 0. 0. 0.]
  [0. 0.

In [16]:
#dowload to colab
#https://askubuntu.com/questions/207265/how-to-download-a-file-from-a-website-via-terminal
!wget  -P /content/ 'http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz'

--2019-10-07 14:05:49--  http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
Resolving yann.lecun.com (yann.lecun.com)... 216.165.22.6
Connecting to yann.lecun.com (yann.lecun.com)|216.165.22.6|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 9912422 (9.5M) [application/x-gzip]
Saving to: ‘/content/train-images-idx3-ubyte.gz’

train-images-idx3-u 100%[===================>]   9.45M  11.0MB/s    in 0.9s    

2019-10-07 14:05:50 (11.0 MB/s) - ‘/content/train-images-idx3-ubyte.gz’ saved [9912422/9912422]

