<a href="https://colab.research.google.com/github/amamra-abdenour/Deep_Learning_Python/blob/master/Learn_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
def fibonacci(a,b,n):
	print (a)
	return fibonacci(b,a+b,n) if b < n else print ('end')

s = 'amamra abdenour'
items = [1, 10, 7, 4, 5, 9]
items[0:3] = ['A', 'B','C'] 
#print(items[-len(items)+2])

a,b = 0,1
#fibonacci(a,b,10)
'''
x= int (input("please enter an integer : "))
if x < 0 :
	x=0
	print("negative changed to zero")
elif x == 0:
	print("zero")
elif x == 1:
	print("single")
else:
	print("more")
words = ['kayfouh', 'lamine', 'nassim']
h=0;
for x in words[:]:
	h = h + 1
	if (len(x) > 6 ):
		words.insert(len(words)+1,x)

print(h,words)
for x in range(10):
	print(x)
print("range(1,10)")
for x in range(1,10):
	print(x)
print("range(1,10,3)")
for x in range(1,10,3):
	print(x)

a = ['Mary', 'had', 'a', 'little', 'lamb']

for i, x in enumerate(a):
	print(i,x)
knights = {'gallahad': 'the pure', 'robin': 'the brave'}
for i,x in knights.items():
	print('key : ',i,'value : ',x)

questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
for q,a in zip(questions,answers):
	print('Question : ',q,'| Answer : ',a)

for x in range(2,10):
	for y in range(2,x):
		if (x%y == 0) :
			print(x,' = ',y,' * ',x//y)
			break
	else:
		print(x ,' is prime')		

for x in range(1,10):
	if x % 2 == 0:
		print(x,'is even')
		continue
	else:
		print(x, 'is odd number')

def fib(n):
	a,b = 0,1 
	result =[]
	while a < n:
		result = result + [a]
		a, b =  b, a+b
	return result
n = int (input("enter n:"))
print(fib(n))

def ask_ok(prompt, retries=4, reminder='Please try again!'):
	while True:
		ok = input(prompt)
		if ok in ['y','yeah','ye','yes']:
			return True
		if ok in ['n','no','np','nope','nop']:
			return False
		retries = retries -1
		if retries < 0 :
			raise ValueError('Invalid user response')	
			print('reminder')
ask_ok("Do you want to continue ...\n")

i=5
def f(arg = i):
	print(arg)

i= 6
f()

def f(a,L=None):
	if L is None:
		L = []
	L.append(a)
	return L

Res = f(1)
print(Res)
print(f(1,Res))
print(f(1))

def f(arg1, arg2 = 'abdenour',arg3='amamra',arg4=10):
	print('arg1 ',arg1)
	print('arg2 ',arg2)
	print('arg3 ',arg3)
	print('arg4 ',arg4)

f(10,arg2='amira',arg3='hennani')

def f(arg1, *arg2 ,**arg3):
	print(type(arg2),arg2)
	for v in arg2:
		print(v)

	print("-" * 40)
	print(type(arg3),arg3)
	for k,v in arg3.items():
		print(k,' ',v)

f('tuple and dictionary',1,2,3,k1='a',k2='b',k3='c')

def f(arg0,arg1,arg2,arg3):
	print(arg0)
	print(arg1)
	print(arg2)
	print(arg3)

arg = ('level0','level1','level2','level3')
d= {'arg0':0,'arg1':1,'arg2':2,'arg3':3}
f(**d)
'''
def make_increment(n: str,x: str=10) ->str:
	""" This function increment a number 'n' by 'x', hence giving n = n + x

	this function is useful for quickly incrementing integers

	print(make_increment.__annotations__)
	return lambda x: x+n
f= make_increment(42)
print(make_increment(42)(x=1))

pairs = [(1, 'one'), (2, 'two'), (3, 'three'), (4, 'four')]
pairs.sort(key= lambda pair: pair[0])
print(pairs)
	
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
#fruits.extend(range(5))
fruits.sort()
fruits.append('cherry')
print (fruits.pop()) 
print (fruits)

from collections import deque
q = deque(range(5))
q.append(0)
print(q)
q.append(-1)
print(q)
q.popleft()
print(q)
q.pop()
print(q)

L = []
L.extend(range(10))
print(L)
squares= [x**2 for x in L]
combination = [(x,y,z) for x in L for  y in L for z in ['x','y','z'] if x != y]
print(combination)

def f(x):
	return abs(x)

vec = [-4, -2, 0, 2, 4]
vec_squared = [x*2 for x in vec]
print(vec_squared)
vec_squared_nnegative = [x for x in vec if x > 0]
print(vec_squared_nnegative)
vec_f = [f(x) for x in vec]
print(vec_f)

freshfruit = ['  banana', '  loganberry ', 'passion fruit  ']
L = [weapon.upper() for weapon in freshfruit]
L = [(x,x**2) for x in range(10)]
vec = [[1,2,3], [4,5,6], [7,8,9]]
L3 = [num for elem in vec for num in elem ]
print(L3)

matrix = [
			[12,25,33],
			[2,3,55],
			[10,10,12]
		]

transpose = [[row[i] for row in matrix] for i in range(3)]
print(transpose)

transpose = []
for i in range(3):
	transpose.append([row[i] for row in matrix])

matrix = [
			[12,25,33],
			[2,3,55],
			[10,10,12]
		]
L = list(zip(*matrix))

L = [12,25,33]
print(L)
del(L) 
print(L)

v = 1,23,5
v=[*v], [*v], [*v]
x = y = z = 33
v = x,y,z
L = tuple([2*x for x in v])
#L = list(L)
x,y,z = L
print(x,y,z,type(L))

s1= {0,1,3,5}
s2= {0,2,4,6}
s3 = {(x,y) for x in s1 for y in s2  if x != y}
print(s3)

dict = {2:'a',2:'b', 22:'b'}
#del (dict[1])
L = sorted(dict)
L = list(dict)
print(dict, L, 3 in dict)

dict = {x:x**2 for x in (5,1,2)}
print(dict)
T = ['a','b','c']
for k,v in dict.items():
	print(k,v)
for x in enumerate(T):
	print(x)

questions = ['name', 'quest', 'favorite color']
answers = ['lancelot', 'the holy grail', 'blue']
for q,a in zip(questions,answers):
	print('The answer to your question ({0}) is {1}'.format(q,a))
for x in reversed(range(1,10)):
	print(x)
for x in sorted(reversed(range(1,10))):
	print(x)

import math
raw_data = [56.2, float('NaN'), 51.7, 55.3, 52.5, float('NaN'), 47.8]
filtered_data=[]
for x in raw_data:
	if not math.isnan(x):
		filtered_data.append(x)
print(raw_data)
print(filtered_data)

str1,str2,str3 = 'ab','cd', 'ef'
not_null = str1 and str2 and str3
print(not_null)

import fibonacci
print(fibonacci.fibo(10))
print(fibonacci.fibo_result(10))

from fibonacci import fibo, fibo_result
print(fibo(10))
print(fibo_result(10))

from fibonacci import *
print(fibo(10))
print(fibo_result(10))

import fibonacci as fb
print(fb.fibo(10))
print(fb.fibo_result(10))

from fibonacci import fibo as fb
from fibonacci import fibo_result as fb_res
print(fb(10))
print(fb_res(10))

year = 2016
event = 'hallowean'
print('the event {0} takes place in the year {1}'.format(year,event))

s= 'Hello world'
print(str(s))
print(repr(s))
print(str(1/7))
x = 10 *10
y = 4 * 12.25
print('the value of x = '+repr(x)+ ' and value of y is '+repr(y) +' ....')

hello = 'hello world \n'
hellos = repr(hello)
print(hello)
print(hellos)
repr(hello)

import math
print(F"the value of pi is : {math.pi:.3f}")

table = {'Sjoerd': 4127, 'Jack': 4098, 'Dcab': 7678}
for name, phone in table.items():
	print(f'{name:3} ==>{phone:3d}')

animals = 'eels'
print(f'my bag is full of {animals!r}')

print ('We are the {food} who say {fee}'.format(food='nights',fee='Ni'))
print ('We are the {0} who say {1}'.format('nights','Ni'))
print ('We are the {1} who say {0}'.format('nights','Ni'))

for x in range(1,10):
	print('{0:2d},{1:3d},{2:4d}'.format(x,x*x,x*x*x))
  """
with  open("/content/drive/My Drive/Colab Notebooks/workFile",'w') as f:
  f.write('The % operator can also be used for string formatting. It interprets\n'+ 
          'the left argument much like a sprintf()-style format string to be applied\n' +  
          'to the right argument, and returns the string resulting from this\n'+
          'formatting operation. For example:\n')
f.close()


In [0]:
with  open("/content/drive/My Drive/Colab Notebooks/workFile",'r') as f:
  read_data_1 = f.readline()
  read_data_2 = f.readline()
  read_data_3 = f.readline()
  print(read_data_1)
  print(read_data_2)
  print(read_data_3)
f.close()

The % operator can also be used for string formatting. It interprets

the left argument much like a sprintf()-style format string to be applied

to the right argument, and returns the string resulting from this



In [0]:
f = open("/content/drive/My Drive/Colab Notebooks/workFile",'r')
#Lf = list(f)
for line in f:
  print(line)
#print(Lf)
f.close()

The % operator can also be used for string formatting. It interprets

the left argument much like a sprintf()-style format string to be applied

to the right argument, and returns the string resulting from this

formatting operation. For example:



In [0]:
f = open("/content/drive/My Drive/Colab Notebooks/workFile",'w')
f.write(str(45))
f.close()

In [0]:
f = open("/content/drive/My Drive/Colab Notebooks/workFile",'r')
line = f.readline()
print(line)
print(f.tell())
f.seek(2)
for line in f:
  print(line)

f.close()

The % operator can also be used for string formatting. It interprets

69
e % operator can also be used for string formatting. It interprets

the left argument much like a sprintf()-style format string to be applied

to the right argument, and returns the string resulting from this

formatting operation. For example:



In [0]:
#binary files
f = open('workFileBinary','wb')
print(f.write(b'0123456789abcdef'))
f.close()

16


In [0]:
f = open('workFileBinary','rb')
l = f.readline()
print(l)
f.close()

b'0123456789abcdef'


In [0]:
f = open('workFileBinary','rb')
f.seek(10)
w1 = f.read(1)
print(w1)
f.close()


b'a'


In [0]:
import json
f = open('workFile_Json','w')
L = ['1','2','3']
json.dump(L, f)
f.close()

In [0]:
import json
f = open('workFile','r')
L = json.load(f)
f.close()
print(L)

['1', '2', '3']


In [0]:
while True:
  try :
    x = int(input("Entre a number : "))
    break
  except ValueError:
    print("That was not a valid number, try again ...")

Entre a number : l
That was not a valid number, try again ...
Entre a number : l
That was not a valid number, try again ...
Entre a number : 
That was not a valid number, try again ...
Entre a number : 15


In [0]:
import numpy as np
print('amamra'.format())

amamra


In [0]:
import sys 
try:
  f = open('data.txt','r')
  s = f.readline()
  i = int(s.strip())
  print("Read with success {0}".format(i))
except OSError as err:
  print("OS erro : {0}".format(err))
except ValueError :
  print("Could not convert value to int")
except :
  print("Unexpected error")
  raise
f.close()

Read with success 12


In [0]:
for arg in sys.argv[1:]:
  try:
    f = open(arg, 'r')
  except OSError as err:
    print("OS error : {0}".format(err))
  else:
    print(arg,' has ', len(f.readlines()),'lines' )
    f.close()

OS error : [Errno 2] No such file or directory: '-f'
/root/.local/share/jupyter/runtime/kernel-279bf421-3402-467c-a44b-8820c99d1b52.json  has  12 lines


In [0]:
def this_fails():
  return 1/0
try:
  this_fails()
except ZeroDivisionError as err:
  print("handling run time error : {}".format(err))
  print("handling run time error : ",err)


handling run time error : division by zero
handling run time error :  division by zero


In [0]:
#Rainsing exception
raise NameError('Hi there')

NameError: ignored

In [0]:
raise ValueError('Raising value error')

ValueError: ignored

In [0]:
def divide(x,y):
  try:
    result = x/y
  except ZeroDivisionError as  err:
    print(err)
  except TypeError as err:
    print(err)
  else: 
    print("Result: " , result)
  finally:
    print("Leaving function")
divide(8,7)
divide(8,0)
divide(8,'e')



Result:  1.1428571428571428
Leaving function
division by zero
Leaving function
unsupported operand type(s) for /: 'int' and 'str'
Leaving function


In [0]:
def scope_test():
  def do_local():
    spam = "local spam"

  def do_nonlocal():
    nonlocal spam
    spam = "nonlocal spam"

  def do_global():
    global spam
    spam = "global spam"

  spam = "test spam"
  do_local()
  print("After local assignment",spam)
  do_nonlocal()
  print("After non local assignment",spam)
  do_global()
  print("After global assignment",spam)

scope_test()
print("In global scope",spam)

After local assignment test spam
After non local assignment nonlocal spam
After global assignment nonlocal spam
In global scope global spam


In [0]:
class MyClass:
  """A simple class definition"""
  def __init__(self):
    self.data = []
    print("Constructor call")

  i = 12
  def f():
    return "f"
print(MyClass.i, MyClass.f)
print(MyClass.__doc__)
C = MyClass()

12 <function MyClass.f at 0x7fbbed59e950>
A simple class definition
Constructor call


In [0]:
class Complex:
  def __init__(self, realpart, imagpart):
    self.r = realpart
    self.i = imagpart

x = Complex(5.0, 6.0)
print(x.r, x.i)

5.0 6.2


In [0]:
class Dog:
  kind = 'canine'
  
  def __init__(self, name):
    self.name = name
    self.tricks = []
  
  def add_trick(self, trick):
    self.tricks.append(trick)
  


a = Dog('Rex')
b = Dog('Jack')
a.add_trick('Roll over')
b.add_trick('Roll back')
print(a.tricks)
print(b.tricks)

['Roll over']
['Roll back']


In [0]:
a = 13
type(a)

int

In [0]:
class C:
    @classmethod
    def f(cls):
      print("f")

C.f()

f


In [0]:
class SomeClass:
    def create_arr(self): # An instance method
        self.arr = []
    
    def insert_to_arr(self, value):  #An instance method
        self.arr.append(value)
        
    @classmethod
    def class_method(cls):
        print("the class method was called")
SomeClass.class_method()

the class method was called


In [0]:
res_1 = (x for x in range(10))
res_2 = (x*x for x in range(10))
res_3 = ((x,y) for x,y in zip(range(2),range(2)))
print(*res_1)
print(*res_2)
print(*res_3)

0 1 2 3 4 5 6 7 8 9
0 1 4 9 16 25 36 49 64 81
(0, 0) (1, 1)


In [0]:
from math import sin, pi
sin_table = {x:sin(x*pi/180) for x in range(0,10)}
print(sin_table)

{0: 0.0, 1: 0.01745240643728351, 2: 0.03489949670250097, 3: 0.05233595624294383, 4: 0.0697564737441253, 5: 0.08715574274765817, 6: 0.10452846326765346, 7: 0.12186934340514748, 8: 0.13917310096006544, 9: 0.15643446504023087}


In [0]:
res_3 = set((x,y) for x,y in zip(range(2),range(2)))
print(res_3.__class__)

<class 'set'>


In [0]:
def reverse_data(data):
  for index in range(len(data)-1, -1, -1):
    yield data[index]
L = range(10)
for l in reverse_data(L):
  print(l)

9
8
7
6
5
4
3
2
1
0


In [0]:
for element in [1,2,3,4]:
  print(element)

1
2
3
4


In [0]:
for element in (1,2,3,4):
  print(element)

1
2
3
4


In [0]:
for k, v in {1:'a',2:'b',3:'c',4:'d'}.items():
  print(k,v)

1 a
2 b
3 c
4 d


In [0]:
L = range(10)
print(list(enumerate(L)))

[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]


In [0]:
L = ["a","b","c"]
for idx, elem in enumerate(L):
  print(idx,elem)

0 a
1 b
2 c


In [0]:
#List to array
from array import array
L = list(range(10))
L.append('a')
print(str(L))
A_L = array('i',L)
print(A_L)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 'a']


TypeError: ignored

In [0]:
s= "ama"
it = iter(s)
print(next(it))
print(next(it))
print(next(it))
print(next(it))

a
m
a


StopIteration: ignored

In [0]:
class Reverse:
  def __init__(self, data):
    self.data = data
    self.index = len(data)
  
  def __iter__(self):
    return self

  def __next__(self):
    if self.index == 0 :
      raise StopIteration
    self.index -=  1
    return self.data[self.index]
  next = __next__
s = "hello"
rev = Reverse(s)
#print(iter(rev))
#it = iter(rev)
print(rev.next())
print(rev.next())
print(rev.next())

o
l
l


In [0]:
import os
print(os.getcwd())
f = os.system('ls')
print(f)

/content
0


In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
for dir in os.walk(os.getcwd()):
  print(dir)

('/content', ['.config', 'drive', 'sample_data'], [])
('/content/.config', ['configurations', 'logs'], ['active_config', 'gce', '.last_update_check.json', 'config_sentinel', '.metricsUUID'])
('/content/.config/configurations', [], ['config_default'])
('/content/.config/logs', ['2019.08.27'], [])
('/content/.config/logs/2019.08.27', [], ['16.17.00.530950.log', '16.17.22.686467.log', '16.17.21.663235.log', '16.17.17.407104.log', '16.17.07.367707.log'])
('/content/drive', ['My Drive', '.Trash'], [])
('/content/drive/My Drive', ['THESIS2015', 'FilterRegistration', 'Hotels', 'Shared', 'TRAVEL', 'SIVP', 'SCANNED DOC', 'AMIRA', 'ABDENOUR', 'Smooth Real Time Head Tracking for Virtual Reality Applications_2', 'Colab Notebooks', 'FEDCSIS2019', 'vopo.easyhomefinance'], ['Thesis2014Lounisfinal.docx', 'LounisChermakThesis2014.docx', 'Thesis2014Lounisfinal.docx.gdoc', 'Nouveau Programme Ingénieur Genie Informatique.pdf', 'DACPR001_DACI-JPA14817_0040_001.pdf', 'VFS Response Mail.pdf', 'VFS Response 

In [0]:
from pathlib import Path
wd_path = Path(os.getcwd())
wd_path_parent = wd_path.parent
print(wd_path_parent.parent)

/


In [0]:
#CS231 Python
x = 10.0
print(type(x))
print(x + 1)
print(x - 1)
print(x**2)
x += 1
print(x)
x *= 2
print(x)
print(x, 2*x,x**3)

<class 'float'>
11.0
9.0
100.0
11.0
22.0
22.0 44.0 10648.0


In [0]:
b1 = True
b2 = False
print(type(b1))
print(b1 and b1)
print(b1 or b2)
print(not True)
t = not b1
print(b1 != t)

<class 'bool'>
True
True
False
True


In [0]:
s1 = 'hello'
s2 = 'world'
print(s1 +' '+ s2)
h = '%s %s %d'%(s1, s2, 12)
print(h)

hello world
hello world 12


In [0]:
l = [1, 2, 3]
l.append('abc')
print(l[-1])
print(l.pop())
print(l)

abc
abc
[1, 2, 3]


In [0]:
l = list(range(3))
print(l)
print(l[:])
print(l[0:])
print(l[:-1])
l[0:1] = ['a', 'b']
print(l)

[0, 1, 2]
[0, 1, 2]
[0, 1, 2]
[0, 1]
['a', 'b', 1, 2]


In [0]:
animals= ['dog', 'cat', 'monkey']
for animal in animals:
  print(animal)

dog
cat
monkey


In [0]:
for i, animal in enumerate(animals):
  print('idx %d corresponds to %s'%(i, animal))

idx 0 corresponds to dog
idx 1 corresponds to cat
idx 2 corresponds to monkey


In [0]:
l = list(range(5))
squares = []
for e in l:
  squares.append(e**2)
print(squares)

[0, 1, 4, 9, 16]


In [0]:
squares = [x**2 for x in l]
print(squares)

[0, 1, 4, 9, 16]


In [0]:
squares_odd=[]
squares_odd = [x**2 for x in l if x % 2 == 0]
print(squares_odd)

[0, 4, 16]


In [0]:
dict = {1:'cat', 2:'dog', 3:'horse'}
for key, value in dict.items():
  print(key, value)
print(dict[1])
print(2 in dict)

1 cat
2 dog
3 horse
cat
True


In [0]:
d = {x:x**2 for x in range(10) if x % 2 != 0}
print(d)

{1: 1, 3: 9, 5: 25, 7: 49, 9: 81}


In [0]:
s = {x for x in range(10)}
print(s, type(s))
print(2 in s)
s.add(12)
print(s)
s.remove(2)
print(len(s))

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9} <class 'set'>
True
{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 12}
10


In [0]:
s = {x**2 for x in range(10) if x // 5 > 0}
print(s)
print(s)
for i, x in enumerate(s):
  print(i, x)

{64, 36, 81, 49, 25}
{64, 36, 81, 49, 25}
0 64
1 36
2 81
3 49
4 25


In [0]:
t = (1,2,2)
print(type(t),t)

<class 'tuple'> (1, 2, 2)


In [0]:
def sign(x, do=True):
  if do:
    if x > 0 :
      return 'positive' 
    elif x < 0 :
      return 'negative' 
    else :
      return 'zero'
  else:
    return '?'

for x in [-1, 0, 1]:
  print(sign(x, False))

?
?
?


In [0]:
class Greeter(object):
  def __init__(self, name):
    self.name = name
  
  def greet(self, loud=False):
    if loud:
      print('HELLO %s'%(self.name.upper()))
    else:
      print('hello %s'%(self.name))
f = Greeter("Fred")
f.greet()
f.greet(True)


hello Fred
HELLO FRED


In [3]:
import numpy as np
a = np.array([1, 2, 3])
print(a)
print(a.shape)
print(a[0])
B = np.array([[1, 2], [3, 2]])
print(B)
print(B[0,0])

[1 2 3]
(3,)
1
[[1 2]
 [3 2]]
1


In [6]:
from numpy.random import random
a = np.zeros((3,3))
print(a)

a = np.ones((3,3))
print(a)

a = np.eye((3))
print(a)

a = np.random.random((3,3))
print(a)

a = np.full((2, 2), 7.)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.98856932 0.52735122 0.13143576]
 [0.77249162 0.37565219 0.70532493]
 [0.25278001 0.04541928 0.34616581]]
[[7. 7.]
 [7. 7.]]


In [8]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]  ])
print(a)
b = a[:2,1:3]
b[0, 0] = 0
print(b)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[0 3]
 [6 7]]
[[ 1  0  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
r_1 = a[1, :]
r_2 = a[1:2, :]
print(r_1, r_1.shape)
print(r_2, r_2.shape)

c_1 = a[:, 1]
c_2 = a[:, 1:2]
print(c_1, c_1.shape)
print(c_2, c_2.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 0  6 10] (3,)
[[ 0]
 [ 6]
 [10]] (3, 1)


In [14]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a.shape)
print(a[[0,1,2],[0,1,0]])
print(a[[0,0], [1,1]])

(3, 2)
[1 4 5]
[2 2]


In [20]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
b = np.array([0, 2, 0, 1])
print(a[np.arange(4), b])
a[np.arange(4), b] *= 100
print(a)

[ 1  6  7 11]
[[ 100    2    3]
 [   4    5  600]
 [ 700    8    9]
 [  10 1100   12]]


In [22]:
print(a[a > 4])

[ 100    5  600  700    8    9   10 1100   12]
