<a href="https://colab.research.google.com/github/amamra-abdenour/Deep_Learning_Python/blob/master/Multilayer_Perceptron_(MLP)_for_multi_class_softmax_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import keras
from keras import Sequential
from keras.layers import Dense, Dropout, Activation
from keras.optimizers import SGD
import numpy as np

#step 0  data preparation
x_train = np.random.rand(1000,20)
y_train = np.random.randint(10, size=(1000,1))
y_train = keras.utils.to_categorical(y_train,num_classes=10) 

x_test = np.random.rand(100,20)
y_test = np.random.randint(10, size=(100,1))
y_test = keras.utils.to_categorical(y_test,num_classes=10) 

for i in range(10):
  print(y_test[i])
#step 1 network architecture
model = Sequential()
model.add(Dense(64, activation='relu', input_dim=20))
model.add(Dropout(0.5))
model.add(Dense(64, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(10,activation='softmax'))
#step 2 optimizer setting
sgd= SGD(lr=0.01,decay=1e-6, momentum=0.9, nesterov=True)
model.compile(optimizer=sgd,
              loss='categorical_crossentropy',
              metrics=['accuracy'])
#setp 3 train
model.fit(x_train,y_train,epochs=20,batch_size=128)
#step 4 test
print(model.metrics_names)
model.evaluate(x_test,y_test,batch_size=128)

[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
Epoch 1/20
1000/1000 [==============================] - 0s 416us/step - loss: 2.4090 - acc: 0.1060
Epoch 2/20
1000/1000 [==============================] - 0s 21us/step - loss: 2.3607 - acc: 0.1040
Epoch 3/20
1000/1000 [==============================] - 0s 24us/step - loss: 2.3371 - acc: 0.1250
Epoch 4/20
1000/1000 [==============================] - 0s 26us/step - loss: 2.3261 - acc: 0.0940
Epoch 5/20
1000/1000 [==============================] - 0s 23us/step - loss: 2.3189 - acc: 0.1140
Epoch 6/20
1000/1000 [==============================] - 0s 23us/step - loss: 2.3124 - acc: 0.1030
Epoch 7/20
1000/1000 [==============================] - 0s 22us/step - loss: 2.3124 - acc: 

[2.3018434047698975, 0.05999999865889549]